import { Badge } from '../components/Badge.jsx';
import { Icon } from '../components/Icon.jsx';
import { reviewItems } from '../data/mockData.js';

const selected = reviewItems[0];

function PlatformChip({ channel }) {
  const normalized = channel.toLowerCase();
  const label = normalized.includes('linkedin') ? 'LinkedIn' : normalized.includes('x') ? 'Twitter / X' : channel;
  const mark = normalized.includes('linkedin') ? 'in' : normalized.includes('x') ? 'X' : 'C';

  return (
    <span className="platform-chip">
      <span className={mark === 'in' ? 'platform-dot linkedin-dot' : mark === 'X' ? 'platform-dot x-dot' : 'platform-dot community-dot'}>{mark}</span>
      {label}
    </span>
  );
}

export function ReviewQueuePage() {
  return (
    <div className="review-queue-page">
      <header className="review-workspace-header">
        <div>
          <h1>Human-in-the-loop Review</h1>
          <p>Manage pending artifacts and manual moderation tasks.</p>
        </div>
        <div className="page-actions">
          <button type="button">
            <Icon name="filter_list" />
            Filter
          </button>
          <button type="button">
            <Icon name="sort" />
            Sort
          </button>
        </div>
      </header>

      <div className="review-split-layout">
        <section className="review-table-shell">
          <nav className="review-tabs" aria-label="Review status filters">
            {['All', 'Pending', 'Approved', 'Changes Requested', 'Rejected'].map((tab, index) => (
              <button className={index === 1 ? 'active' : ''} key={tab} type="button">
                {tab}
                {tab === 'Approved' ? <span>12</span> : null}
              </button>
            ))}
          </nav>

          <div className="review-table-scroll">
            <table className="dense-table review-table">
              <thead>
                <tr>
                  <th>Review ID</th>
                  <th>Artifact</th>
                  <th>Platform</th>
                  <th>Risk</th>
                  <th>Status</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {reviewItems.slice(0, 8).map((item, index) => (
                  <tr className={index === 0 ? 'selected-row' : ''} key={item.id}>
                    <td>{`#RQ-${8422 - index}`}</td>
                    <td>
                      <strong>{item.label}</strong>
                      <span>{item.source} review check</span>
                    </td>
                    <td>
                      <PlatformChip channel={item.channel} />
                    </td>
                    <td>
                      <Badge tone={item.risk === 'High' ? 'danger' : item.risk === 'Low' ? 'success' : 'warning'}>{item.risk}</Badge>
                    </td>
                    <td>
                      <Badge tone="neutral">{item.status}</Badge>
                    </td>
                    <td>
                      <button type="button">
                        <Icon name={index === 0 ? 'chevron_right' : 'open_in_new'} />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <aside className="review-drawer">
          <header>
            <div>
              <div className="drawer-title-row">
                <h2>Review #RQ-8422</h2>
                <Badge tone={selected.risk === 'High' ? 'danger' : 'warning'}>{selected.risk} Risk</Badge>
              </div>
              <p>Generated by Social-Agent policy workflow</p>
            </div>
            <button type="button">
              <Icon name="close" />
            </button>
          </header>

          <div className="drawer-meta-grid">
            <article>
              <span>Target Platform</span>
              <strong>{selected.channel}</strong>
            </article>
            <article>
              <span>Scheduled For</span>
              <strong>Oct 24, 14:00</strong>
            </article>
          </div>

          <div className="drawer-scroll">
            <section className="policy-alert">
              <Icon name="warning" />
              <div>
                <h3>Healthcare Review Flag</h3>
                <p>The selected item is close to clinical, privacy, or crisis-sensitive language and requires human approval before package handoff.</p>
              </div>
            </section>

            <section>
              <h3 className="drawer-section-title">
                Draft Content Preview
                <button type="button">
                  <Icon name="edit" />
                  Edit Source
                </button>
              </h3>
              <div className="review-preview-card">
                <div className="fake-post-header">
                  <div className="fake-avatar" />
                  <div>
                    <strong>Context-Med</strong>
                    <span>@contextmed - Draft</span>
                  </div>
                </div>
                <p>{selected.quote}</p>
                <div className="attached-media">Attached package artifact preview</div>
              </div>
            </section>

            <section>
              <h3 className="drawer-section-title">Reviewer Notes</h3>
              <textarea placeholder="Add justification for approval, rejection, or requested changes..." />
            </section>
          </div>

          <footer>
            <button className="danger-button" type="button">Reject</button>
            <button type="button">Request Changes</button>
            <button className="primary" type="button">
              <Icon name="check_circle" />
              Approve
            </button>
          </footer>
        </aside>
      </div>
    </div>
  );
}
